# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: "https://github.com/pre-commit/mirrors-prettier"
      rev: "v2.4.1"
      hooks:
          - id: "prettier"
            name: "Format Markdown"
            tags: ["md"]
    - repo: "git://github.com/doublify/pre-commit-clang-format"
      rev: "62302476d0da01515660132d76902359bed0f782"
      hooks:
          - id: "clang-format"
