name: "Build and Test"
on: ["push", "pull_request"]

jobs:
    RunTestsOnMacLua53:
        name: "MacOS (Latest) - Lua 5.3"
        runs-on: "macos-latest"
        steps:
            - uses: "actions/checkout@v2"
            - name: "Add Dependencies"
              run: |
                  brew install lua luarocks
                  luarocks install busted
            - name: "Build Project"
              run: "luarocks make"
            - name: "Test Project"
              run: "busted"
    RunTestsOnLinuxLua51:
        name: "Ubuntu (Latest) - Lua 5.1"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v2"
            - name: "Add Dependencies"
              run: |
                  sudo apt install luarocks liblua5.1-0-dev lua5.1
                  sudo luarocks install busted
            - name: "Build Project"
              run: "sudo luarocks make"
            - name: "Test Project"
              run: "busted"
    RunTestsOnLinuxLua52:
        name: "Ubuntu (Latest) - Lua 5.2"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v2"
            - name: "Add Dependencies"
              run: |
                  sudo apt install luarocks liblua5.2-dev lua5.2
                  sudo luarocks install busted
            - name: "Build Project"
              run: "sudo luarocks make"
            - name: "Test Project"
              run: "busted"
    RunTestsOnLinuxLua53:
        name: "Ubuntu (Latest) - Lua 5.3"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v2"
            - name: "Add Dependencies"
              run: |
                  sudo apt install luarocks liblua5.3-dev lua5.3
                  sudo luarocks install busted
            - name: "Build Project"
              run: "sudo luarocks make"
            - name: "Test Project"
              run: "busted"
    RunTestsOnLinuxLuaJIT:
        name: "Ubuntu (Latest) - LuaJIT"
        runs-on: "ubuntu-latest"
        steps:
            - uses: "actions/checkout@v2"
            - name: "Add Dependencies"
              run: |
                  sudo apt install luarocks luajit libluajit-5.1-dev libluajit-5.1-2
                  sudo luarocks install busted
            - name: "Build Project"
              run: "sudo luarocks make"
            - name: "Test Project"
              run: "busted"
